import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { computeCommodityStats, distributionTotalQty } from "../data/mockData.js";

const BRAND_GREEN = [47, 158, 68];
const TEXT_MUTED = [107, 122, 112];

function addHeader(doc, title, { dateFrom, dateTo }) {
  doc.setFillColor(...BRAND_GREEN);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 22, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont(undefined, "bold");
  doc.text("AgriShare", 14, 14);
  doc.setFontSize(9);
  doc.setFont(undefined, "normal");
  doc.text("Municipality of Labangan — Barangay Langapud", 14, 19);

  doc.setTextColor(20, 30, 25);
  doc.setFontSize(13);
  doc.setFont(undefined, "bold");
  doc.text(title, 14, 32);

  doc.setFontSize(9);
  doc.setTextColor(...TEXT_MUTED);
  doc.setFont(undefined, "normal");
  const generated = new Date().toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" });
  doc.text(`Date Range: ${dateFrom} to ${dateTo}`, 14, 38);
  doc.text(`Generated: ${generated}`, 14, 43);

  return 50;
}

function addFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...TEXT_MUTED);
    doc.text(
      "Generated by AgriShare — for internal MAO/FA President use only.",
      14,
      doc.internal.pageSize.getHeight() - 8,
    );
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.getWidth() - 30, doc.internal.pageSize.getHeight() - 8);
  }
}

function buildBeneficiaryList(doc, y, { farmers, barangay, commodity }) {
  const rows = farmers
    .filter((f) => (barangay === "All Barangays" ? true : f.barangay === barangay))
    .filter((f) => (commodity === "All Commodities" ? true : f.commodity === commodity))
    .map((f) => [f.rsbsaNo, `${f.firstName} ${f.lastName}`, f.barangay, f.commodity, f.status]);

  autoTable(doc, {
    startY: y,
    head: [["RSBSA No.", "Full Name", "Barangay", "Commodity", "Status"]],
    body: rows,
    headStyles: { fillColor: BRAND_GREEN },
    styles: { fontSize: 9 },
  });
}

function buildDistributionSummary(doc, y, { distributions, barangay }) {
  const rows = distributions
    .filter((d) => (barangay === "All Barangays" ? true : d.barangay === barangay))
    .map((d) => [d.id, d.date, d.program, d.barangay, String(d.beneficiaries), `${distributionTotalQty(d).toLocaleString()} kg`, d.status]);

  autoTable(doc, {
    startY: y,
    head: [["Distribution ID", "Date", "Program", "Barangay", "Beneficiaries", "Quantity", "Status"]],
    body: rows,
    headStyles: { fillColor: BRAND_GREEN },
    styles: { fontSize: 8.5 },
  });
}

function buildLiquidationReport(doc, y, { commodities, distributions }) {
  const { totals } = computeCommodityStats(commodities, distributions);
  const rows = commodities.map((c) => [c.id, c.name, c.category, `${(totals[c.name] ?? 0).toLocaleString()} kg`]);

  autoTable(doc, {
    startY: y,
    head: [["Commodity ID", "Name", "Category", "Total Distributed"]],
    body: rows,
    headStyles: { fillColor: BRAND_GREEN },
    styles: { fontSize: 9 },
  });
}

function buildAccomplishmentReport(doc, y, { farmers, distributions, commodities }) {
  const totalQty = distributions.reduce((sum, d) => sum + distributionTotalQty(d), 0);
  const active = farmers.filter((f) => f.status === "Active").length;
  const validated = farmers.filter((f) => f.validationStatus === "Validated").length;

  const rows = [
    ["Total Registered Farmers", String(farmers.length)],
    ["Active Farmers", String(active)],
    ["Validated Farmers", `${validated} (${Math.round((validated / (farmers.length || 1)) * 100)}%)`],
    ["Total Distribution Activities", String(distributions.length)],
    ["Total Quantity Distributed", `${totalQty.toLocaleString()} kg`],
    ["Commodity Types Available", String(commodities.length)],
  ];

  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value"]],
    body: rows,
    headStyles: { fillColor: BRAND_GREEN },
    styles: { fontSize: 10 },
    columnStyles: { 0: { fontStyle: "bold" } },
  });
}

const BUILDERS = {
  "Beneficiary List": buildBeneficiaryList,
  "Distribution Summary": buildDistributionSummary,
  "Liquidation Report": buildLiquidationReport,
  "Accomplishment Report": buildAccomplishmentReport,
};

// Builds a jsPDF document for the given report type using whatever farmer/
// distribution/commodity data is passed in. This is a client-side
// reconstruction from current data — it does not store the exact snapshot
// that existed the moment a past "Recent Reports" row was generated, which
// is fine for a mock system but is a real limitation to flag if this needs
// point-in-time accuracy once a backend exists.
function buildReportPdf({ reportType, dateFrom, dateTo, commodity = "All Commodities", barangay = "All Barangays", farmers, distributions, commodities }) {
  const doc = new jsPDF();
  const startY = addHeader(doc, reportType, { dateFrom, dateTo });
  const builder = BUILDERS[reportType] ?? buildAccomplishmentReport;
  builder(doc, startY, { farmers, distributions, commodities, commodity, barangay });
  addFooter(doc);
  return doc;
}

export function downloadReportPdf(params) {
  const doc = buildReportPdf(params);
  const fileSafeType = params.reportType.replace(/\s+/g, "_");
  doc.save(`AgriShare_${fileSafeType}_${params.dateFrom}_to_${params.dateTo}.pdf`);
}

export function previewReportPdf(params) {
  const doc = buildReportPdf(params);
  const blobUrl = doc.output("bloburl");
  window.open(blobUrl, "_blank", "noopener,noreferrer");
}
